// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eSHiknYGb4WLC3QGLYLFnQ
// Component: A3je2_yhMh6rvk

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: UvDP15VkVO5hmb/component
import ServiceWhite from "../../ServiceWhite"; // plasmic-import: h9Deuef5XKQXuA/component
import BlueBdr from "../../BlueBdr"; // plasmic-import: FQ-Q35VXL2xeid/component
import ServiceDark from "../../ServiceDark"; // plasmic-import: iZiKFaA41wnFXi/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: Sh8nt7GR3decD/component
import FooterMain from "../../FooterMain"; // plasmic-import: I_5el5M-Bk81Xi/component

import { useScreenVariants as useScreenVariantspgBiFjijh7ROsO } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PgBiFjijh7ROsO/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_seodapop_main_website.module.css"; // plasmic-import: eSHiknYGb4WLC3QGLYLFnQ/projectcss
import sty from "./PlasmicServices.module.css"; // plasmic-import: A3je2_yhMh6rvk/css

export type PlasmicServices__VariantMembers = {};
export type PlasmicServices__VariantsArgs = {};
type VariantPropType = keyof PlasmicServices__VariantsArgs;
export const PlasmicServices__VariantProps = new Array<VariantPropType>();

export type PlasmicServices__ArgsType = {};
type ArgPropType = keyof PlasmicServices__ArgsType;
export const PlasmicServices__ArgProps = new Array<ArgPropType>();

export type PlasmicServices__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  aboutUsBanner?: p.Flex<"div">;
  foreground2?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  serviceRow?: p.Flex<"div">;
  serviceRow2?: p.Flex<"div">;
  serviceRow3?: p.Flex<"div">;
  footerTopSection?: p.Flex<"div">;
  homeFooterTop?: p.Flex<typeof HomeFooterTop>;
  footerMain?: p.Flex<typeof FooterMain>;
};

export interface DefaultServicesProps {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicServices__RenderFunc(props: {
  variants: PlasmicServices__VariantsArgs;
  args: PlasmicServices__ArgsType;
  overrides: PlasmicServices__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspgBiFjijh7ROsO()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicServices.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicServices.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicServices.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"aboutUsBanner"}
            data-plasmic-override={overrides.aboutUsBanner}
            className={classNames(projectcss.all, sty.aboutUsBanner)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vTpKz)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Services"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__p14UA
                  )}
                >
                  {hasVariant(globalVariants, "screen", "sm")
                    ? "Lorem Ipsum is simply dummy text of the printing and typesetting indstandard dummy text ever since the 1500s."
                    : "We offer a wide variety of services for both marketing and Application development."}
                </div>
              </p.Stack>
            </p.Stack>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__l2DWg)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__fJ1Nh)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__oZdWq)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__buFN)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__iu7Hm
                    )}
                  >
                    {"Online Marketing"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eixxt
                    )}
                  >
                    {
                      " We believe that all the efforts of improvement should come together as a whole. When we do your marketing we want to make sure your website is running properly too. That is why we offer you a series of alternatives to make your website the most efficient. The Inbound Marketing Packages we offer come in different “sizes” to accommodate your needs but in essence they all work the same. What we do for your business is literally make it “Visible”.  We will make a campaign to make you come up at the top of the Google search or any other platform of your preference. Be it Google, Bing, Facebook, Instagram, we can make you come up atop the platform your business will profit the most from.\n\nWe believe in a holistic approach to improving your business. When we handle your marketing, we also ensure your website is running smoothly. Our Inbound Marketing Packages offer different options to suit your needs, but they all share the same goal: making your business visible. We'll create campaigns to boost your presence on platforms like Google, Bing, Facebook, or Instagram—whichever platform brings you the most benefit. With our expertise, we'll help you rise to the top of search results and get noticed by your target audience. Let's work together to make your business shine online!\n\n"
                    }
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zknGz)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__iPgC)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__ht2Ye
                          )}
                          slot2={
                            "Gone are the days when launching a website guaranteed top-ranking on Google. The online landscape has become highly competitive, making it challenging to secure a prominent position. We possess the right tools and expertise to help you rise above the competition and achieve top rankings on Google. Don't just take our word for it; we have successfully achieved this for our own business as well. We would be delighted to showcase our work and discuss how we can help your business thrive. Give us a call today to get started."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__bUIxJ
                            )}
                          >
                            {"SEO \nSearch engine optimization"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__aoByr)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__kp4Fy
                          )}
                          slot2={
                            "#Social . This one is the newest trend. These days people spend more time on their social media site than going anywhere else on the internet. If you like to be successful you have to have a social presence in order for your potential customers to see you. We help you setup and post strategically in order to get more customers. We cover all the major social media sites for you such as linked in, Facebook, twitter, and Instagram. \n\n\n"
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__eXD
                            )}
                          >
                            {"SMM \nSocial Media Marketing"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__bi0Kq)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__a9Ih
                          )}
                          slot2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__peQaY
                              )}
                            >
                              {
                                "PPC is like a photography. Maybe you have your cellphone to take a picture but is the picture that your cellphone takes is the same as the picture that a professional photographer takes with DSLR camera? We are that professional photographer that can leverage all ppc platforms power to make sure that you are not wasting money and only the real customers are clicking on your ads.\n\n\n"
                              }
                            </div>
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__fkdIf
                            )}
                          >
                            {"PPC (Pay-per-click optimization)"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___33D32)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__pTq1X
                          )}
                          slot2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__o4MxB
                              )}
                            >
                              {
                                "By utilizing retargeting techniques, we can help you re-engage visitors who have previously shown interest in your services but haven't yet made a decision. Our retargeting campaigns are designed to deliver personalized and compelling messages to these prospects, reminding them of the value you offer and encouraging them to take the next step. With strategic retargeting, we can maximize your chances of converting interested leads into satisfied clients. Let us help you make the most out of your web development efforts through effective retargeting strategies."
                              }
                            </div>
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__quIf6
                            )}
                          >
                            {"RETARGETING"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__rDvQ5)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__jx7E
                          )}
                          slot2={
                            "The way in which people learn and absorb information has drastically changed in the last few years. We now look to the internet to entertain us, distract us and teach us!. An emerging method of education is the use of “whiteboard animated videos” style. This is a simple, yet incredibly effective tool in delivering a message.  Teachers and businesses have taken advantage of this new tool because it is so engaging and effective.​\n\n"
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__u0Eis
                            )}
                          >
                            {"Whiteboard Animated Videos "}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qkxIi)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite___1MfRc
                          )}
                          slot2={
                            "Inbound marketing is a comprehensive approach that encompasses all the services we offer. Its primary objective is to generate client interest in your services, prompting them to contact you directly rather than solely relying on ads or website visits. By leveraging inbound strategies such as content creation, SEO optimization, social media engagement, and lead nurturing, we aim to attract, engage, and convert potential clients into loyal customers. Let us help you harness the power of inbound marketing to achieve lasting success for your business."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__jOJo3
                            )}
                          >
                            {"Inbound Marketing"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___4Fecg)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___0LvCp)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__q7Dr)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8OAlw)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__qN49
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "sm")
                      ? "Service category"
                      : "Technical Counsulting"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jQFbS
                    )}
                  >
                    {
                      "With over 20 years of collective experience in the technology industry, we possess the expertise and knowledge required to address all your technical requirements. Our team is more than capable of handling any challenges or projects you may have. From software development to system integrations, we have a deep understanding of the technology landscape. Rest assured, we will bring our extensive experience to the table to provide you with top-notch solutions and meet your technical needs effectively."
                    }
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qcyLi)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"serviceRow2"}
                    data-plasmic-override={overrides.serviceRow2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__kwQ96)}
                    >
                      {true ? (
                        <ServiceDark
                          className={classNames(
                            "__wab_instance",
                            sty.serviceDark__yfV1L
                          )}
                          slot={
                            "Our expertise allows us to provide you with the optimal tools for your application requirements. We take into account essential factors such as security, cost-efficiency, and performance to ensure that your application architecture is truly top-notch. By carefully considering these aspects and more, we guarantee that your application will excel in its class, delivering exceptional results and exceeding your expectations."
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__eWipQ
                            )}
                          >
                            {"Architectual Design"}
                          </div>
                        </ServiceDark>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__shBx)}
                    >
                      {true ? (
                        <ServiceDark
                          className={classNames(
                            "__wab_instance",
                            sty.serviceDark___5Olkd
                          )}
                          slot={
                            "We'll carefully dig into your code, keeping an eye out for any security vulnerabilities or programming pattern bugs. Once we're done, we'll put together a comprehensive report that breaks down our findings in a laid-back, easy-to-understand manner. Think of it as a friendly chat over a cup of coffee, where we'll share valuable insights to help you fine-tune your application. So sit back, relax, and let us handle the heavy lifting while you gain peace of mind."
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___50FsP
                            )}
                          >
                            {"Code Base Audit"}
                          </div>
                        </ServiceDark>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___4KfVz)}
                    >
                      {true ? (
                        <ServiceDark
                          className={classNames(
                            "__wab_instance",
                            sty.serviceDark__r2UBw
                          )}
                          slot={
                            "Our Experts have extensive knowledge and experience in specific areas of technology and can provide their expertise and opinions during legal proceedings. We can assist in matters such as intellectual property disputes, patent infringement cases, data breaches, software development disputes, and more. It is important to engage an expert witness with the relevant qualifications, expertise, and credibility to effectively support your case in court."
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sLzPj
                            )}
                          >
                            {"Expert Witness In Technology"}
                          </div>
                        </ServiceDark>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___5PhH)}
                    >
                      {true ? (
                        <ServiceDark
                          className={classNames(
                            "__wab_instance",
                            sty.serviceDark__pdAEs
                          )}
                          slot={
                            "At SeodaPop we excel in seamlessly integrating applications with various APIs and services. Our experienced team is skilled in writing clean and efficient code to meet all your integration requirements. Whether you need to connect your application with popular third-party services, payment gateways, social media platforms, or any other APIs, we've got you covered. Our expertise ensures smooth and reliable communication between different systems, enabling enhanced functionality and improved user experiences. Trust us to handle your integration needs with precision and deliver well-written code that seamlessly accommodates all your integration goals."
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wvl3G
                            )}
                          >
                            {"Integrations"}
                          </div>
                        </ServiceDark>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__zvOd)}
                    >
                      {true ? (
                        <ServiceDark
                          className={classNames(
                            "__wab_instance",
                            sty.serviceDark___9HqNz
                          )}
                          slot={
                            "We specialize in conducting comprehensive audits for various compliance standards, including HIPAA, PCI, GDPR, and ADA.  Whether you need to ensure the security and privacy of healthcare data, protect sensitive payment card information, comply with data protection laws in the European Union, or make your application accessible for individuals with disabilities, we've got you covered. Our auditing process will identify any gaps or areas of non-compliance, allowing us to provide actionable recommendations and help you achieve and maintain the necessary standards. Rest assured that your application will meet the compliance requirements relevant to your industry."
                          }
                        >
                          {"Compliance Audit"}
                        </ServiceDark>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__fp32)}
                    >
                      {true ? (
                        <ServiceDark
                          className={classNames(
                            "__wab_instance",
                            sty.serviceDark__in0A
                          )}
                          slot={
                            "If you're looking to upgrade your legacy code to modern standards with a focus on proper architecture, we've got you covered. Our team specializes in transforming outdated codebases into efficient, maintainable, and scalable solutions. We understand the challenges that come with legacy systems, and we're here to help you navigate the upgrade process seamlessly bring it up to date with the latest technologies. Rest assured, we offer our services at an affordable price, ensuring that you receive exceptional value for your investment. Let us handle the code upgrade, so you can enjoy the benefits of a modern, robust, and cost-effective application."
                          }
                        >
                          {"Legacy Upgrades"}
                        </ServiceDark>
                      ) : null}
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__eljaB)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hn8Jh)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__iFInV)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vRb3L)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__lxKr
                    )}
                  >
                    {"Web Application Development"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ujX0Q
                    )}
                  >
                    {
                      "With over two decades of experience and a remarkable track record of building over 100 websites and hosting more than 500 websites, we are highly confident in our ability to deliver exceptional web design services. Our extensive expertise in the field ensures that we will not only meet but exceed your expectations. We understand the importance of a well-crafted website in today's digital landscape, and our team is dedicated to creating visually stunning and user-friendly websites that effectively represent your brand and drive results. You can trust us to bring your vision to life and provide you with a website that leaves a lasting impression on your audience."
                    }
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tiWaz)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"serviceRow3"}
                    data-plasmic-override={overrides.serviceRow3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__c4UEb)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__r5Ago
                          )}
                          slot2={
                            "Our services include authentic web design brought to life by skilled programmers. We offer various options, from cost-effective WordPress templates to comprehensive full-stack web development. Our range of services caters to your specific needs, providing a seamless and engaging user experience. From concept to execution, we handle every aspect of the web development process, ensuring a high-quality result that exceeds your expectations."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__uIajj
                            )}
                          >
                            {"Website Development"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__j3U9E)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__y7W7S
                          )}
                          slot2={
                            "At our company, we specialize in API design and architecture to cater to all your API requirements. Our services include REST-based APIs as well as GraphQL. We take pleasure in assessing your needs and offering you the most suitable APIs to enhance your experience."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__hdkom
                            )}
                          >
                            {"API Design"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__rfj81)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__dbP7
                          )}
                          slot2={
                            "Our web development services cater to both monolithic CMS applications, including WordPress, and modern headless CMS architecture using platforms like sanity.io and contentful. Whether you prefer a traditional or contemporary approach to your web development, we've got you covered."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__g7A3
                            )}
                          >
                            {"CMS Development"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hYRv)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__qqSFh
                          )}
                          slot2={
                            "Our mobile application development services are designed to be compatible with both Android and iPhone, using the popular React Native framework. Whether you need a mobile app for your business or personal use, we have the expertise to deliver high-quality solutions that meet your needs."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__nvvY
                            )}
                          >
                            {"Mobile Application Development "}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__q07Wk)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__zSuDn
                          )}
                          slot2={
                            "As the internet has evolved, it's become increasingly crucial for web applications to be ADA compliant. Despite previous practices, ensuring accessibility for all users is now more important than ever. That's why we offer auditing and modification services to help make your web application ADA compliant. Our team is equipped to assist you in meeting the standards set forth by the Americans with Disabilities Act."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__kMwZy
                            )}
                          >
                            {"ADA Upgrade"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__gmCi0)}
                    >
                      {true ? (
                        <ServiceWhite
                          className={classNames(
                            "__wab_instance",
                            sty.serviceWhite__sjIGu
                          )}
                          slot2={
                            "Our team of UI experts is dedicated to crafting user-friendly designs that work seamlessly for your clients. We understand the importance of creating intuitive interfaces that don't confuse your clients, and we strive to deliver designs that are both aesthetically pleasing and highly functional. Let us help you design a UI that meets the needs of your business and your customers."
                          }
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__uk5Fy
                            )}
                          >
                            {"UI/UX Research and design"}
                          </h3>
                        </ServiceWhite>
                      ) : null}
                    </div>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </div>
          <div
            data-plasmic-name={"footerTopSection"}
            data-plasmic-override={overrides.footerTopSection}
            className={classNames(projectcss.all, sty.footerTopSection)}
          >
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "aboutUsBanner",
    "foreground2",
    "h1",
    "serviceRow",
    "serviceRow2",
    "serviceRow3",
    "footerTopSection",
    "homeFooterTop",
    "footerMain"
  ],
  header: ["header"],
  aboutUsBanner: ["aboutUsBanner", "foreground2", "h1"],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  serviceRow: ["serviceRow"],
  serviceRow2: ["serviceRow2"],
  serviceRow3: ["serviceRow3"],
  footerTopSection: ["footerTopSection", "homeFooterTop"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  aboutUsBanner: "div";
  foreground2: "div";
  h1: "h1";
  serviceRow: "div";
  serviceRow2: "div";
  serviceRow3: "div";
  footerTopSection: "div";
  homeFooterTop: typeof HomeFooterTop;
  footerMain: typeof FooterMain;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicServices__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicServices__VariantsArgs;
    args?: PlasmicServices__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicServices__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicServices__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    serviceRow: makeNodeComponent("serviceRow"),
    serviceRow2: makeNodeComponent("serviceRow2"),
    serviceRow3: makeNodeComponent("serviceRow3"),
    footerTopSection: makeNodeComponent("footerTopSection"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),

    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Service",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
